[application]
name = "super-app"
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "super-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.mycompany"
publisher = "MyCompany"
icon = ["icons/icon.ico"]
resources = ["assets/*"]
